// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxekxuboywmrzhzgpaei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4ZWt4dWJveXdtcnpoemdwYWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NzQwODksImV4cCI6MjA1NTI1MDA4OX0.roDSe9ZlwPoaeYJDT86BUnLj_QSvv18Mg_J4Hs5KgIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);